README.md, examples/query_chassis.go, examples/query_sessions.go, school/client.go, school/common/types.go, school/redfish/computersystem.go, school/redfish/endpoint.go, school/redfish/memory.go, school/redfish/memorymetrics.go, school/redfish/session.go, school/service.go
Hello @stmcginnis 
I've started implementing the authentication via session to gofish. I've added some methods to redfish/session.go and also to services.go using it as a proxy (or wrapper), following the same pattern you've done for the List methods. I will probably finish the session creation today or tomorrow, so I would like to know if you have any preference on how I should organize the code. 
Thanks!!
[]'s
=> Adding support for authentication via session

school/redfish/chassis.go
=> change data type of the chasis thermal and power

.travis.yml, Makefile
This adds the basic Travis config to run unit tests.
=> Add basic TravisCI job to build and run unit tests

client.go
This is based on https://github.com/stmcginnis/gofish/pull/36#discussion_r321977765
=> client: allow an http.Client to be passed in

client.go, common/types.go, examples/reboot.go, redfish/computersystem.go
This PR makes possible to set Boot options, Boot Overrides and Reboot actions via Gofish.
=> Adds Put and Patch interface, also SetBoot and Reset for ComputerSystem

common/message.go, common/types.go, redfish/bios.go, redfish/bios_test.go, redfish/drive.go, redfish/drive_test.go, redfish/eventservice.go, redfish/eventservice_test.go
This adds Bios, Drive, and EventService actions.
=> Add additional actions for several Redfish objects

redfish/bios.go, redfish/drive.go, redfish/eventservice.go, redfish/logservice.go, redfish/logservice_test.go, redfish/manager.go, redfish/manager_test.go, redfish/networkadapter.go, redfish/networkadapter_test.go
This add actions to NetworkAdapter, Manager, LogService, and fixes some typos.
=> More actions

redfish/secureboot.go, redfish/secureboot_test.go, redfish/storage.go, redfish/storage_test.go, swordfish/storagegroup.go, swordfish/storagegroup_test.go, swordfish/storageservice.go, swordfish/storageservice_test.go, swordfish/volume.go, swordfish/volume_test.go
This adds actions to the SecureBoot, Storage, StorageGroup, StorageService, and Volume objects.
=> Add actions to more objects

client.go
This PR will allow the user to easily dump the HTTP traffic for debug and development purposes.
(This was made possible mainly due to #42)
=> Add ability to dump HTTP traffic

client.go, examples/reboot.go, redfish/bios.go, redfish/chassis.go, redfish/computersystem.go, redfish/manager.go, swordfish/storagepool.go, swordfish/volume.go, tools/generate_from_schema.py, tools/redfish-schema/generate_from_schema.py
* fix golang and PEP8 style complaints
* cap() is a golang builtin
* error handling for dumpwriter writes
=> style and minor fixes

redfish/ethernetinterface.go, redfish/manager.go
also add Oem objects to allow application to access Oem data
Signed-off-by: Leslie Qi Wang <leslie.qiwa@gmail.com>
=> enable listing ethernet interfaces function from manager

redfish/computersystem.go
HPE iLO support this reset type
Signed-off-by: Leslie Qi Wang <leslie.qiwa@gmail.com>
=> add GracefulRestart reset type

Makefile, swordfish/classofservice.go, swordfish/dataprotectionloscapabilities.go, swordfish/dataprotectionloscapabilities_test.go, swordfish/datasecurityloscapabilities.go, swordfish/datastorageloscapabilities.go, swordfish/datastorageloscapabilities_test.go, swordfish/endpointgroup.go, swordfish/endpointgroup_test.go, swordfish/fileshare.go, swordfish/fileshare_test.go, swordfish/filesystem.go, swordfish/filesystem_test.go, swordfish/ioconnectivityloscapabilities.go, swordfish/ioconnectivityloscapabilities_test.go, swordfish/ioperformanceloscapabilities.go, swordfish/ioperformanceloscapabilities_test.go, swordfish/spareresourceset.go, swordfish/spareresourceset_test.go, swordfish/storagegroup.go, swordfish/storagegroup_test.go, swordfish/storagepool.go, swordfish/storagepool_test.go, swordfish/volume.go, swordfish/volume_test.go
This updates some of the Swordfish objects for recent changes to the schema. It also adds Update calls to the objects that have read-write properties.
=> Update Swordfish objects and add Update calls for rw

client.go, common/testclient.go, redfish/eventdestination.go, redfish/eventdestination_test.go, redfish/eventservice.go, redfish/eventservice_test.go, redfish/session_test.go
The idea is to expose four new functions in the event service:
**To create an event subscription:**
```
// CreateEventSubscription creates the subscription using the event service.
// destination should contain the URL of the destination for events to be sent.
// eventTypes is a list of EventType to subscribe to.
// httpHeaders is optional and gives the opportunity to specify any arbitrary
// HTTP headers required for the event POST operation.
// oem is optional and gives the opportunity to specify any OEM specific properties,
// it should contain the vendor specific struct that goes inside the Oem session.
// It returns the new subscription URI if the event subscription is created
// with success or any error encountered.
func (eventservice *EventService) CreateEventSubscription( …
```
=> Adding ability to manage the redfish event subscriptions.

client.go
This adds a `Session` field to `ClientConfig`, to pass in session data from a previous run, and `GetSession()` to retrieve it from a client for serialization. Smells slightly cleaner to me, but it's totally untested except that it compiles. If you think this looks like a better approach than simply exporting `Auth`, I'd change my client to use it like this and give it some testing.
=> Add session data to ClientConfig

common/types.go, redfish/manager.go, redfish/manager_test.go
Signed-off-by: Leslie Qi Wang <qiwa@pensando.io>
It is for https://github.com/stmcginnis/gofish/issues/89.
=> expose manager's Links object to allow caller to further process

client.go, client_test.go, common/types.go
Signed-off-by: Leslie Wang <qiwa@pensando.io>
Close https://github.com/stmcginnis/gofish/issues/94
=> return formated error struct for status code 400

redfish/updateservice.go, redfish/updateservice_test.go
Adding oem to redfish update service.
Some changes to get oem for update service as specified in Redfish.
Also, improving the existing unit test to cover the change.
Thanks!
=> Adding oem to redfish update service.

client_test.go
Add more test coverage for the client calls.
=> Expand client test coverage

client.go
Solves #131 issue regarding Multipart upload
=> Multipart bug fixed

redfish/chassis.go, redfish/chassis_test.go
In version v1.2.0 of the spec, `Drives` were added to the `Chassis.Links`
property. But in v1.14.0 of the spec, `Chassis.Drives` was added as a
direct property.
This updates the Chassis.Drives() call to handle either implementation,
preferring the newer method.
Closes: #143
=> Handle Chassis drives returned as Links

serviceroot.go, serviceroot_test.go
Signed-off-by: Leslie Qi Wang <qiwa@pensando.io>
=> add oem property for root service object

redfish/simplestorage.go
Add a name field to distinguish between devices.
=> fix(simple-storage/device): add device name

redfish/bootoption.go, redfish/bootoption_test.go, redfish/computersystem.go
Fixes: https://github.com/stmcginnis/gofish/issues/183
This is my first look at this codebase so please let me know if anything is needed.
Thanks!
=> feat: add bootoption resource

redfish/memory.go
For my use case, I need to recover many memories info and the method ListReferencedMemorys is too slow beacuse calls the GetMemory sequentially. 
This pull request recovers the memories using channel and goroutine.
=> Update ListReferencedMemorys to recover the memories asynchronously

tools/generate_from_schema.py
Improved desc handling; improved object type handling; improved code formatting.
=> Further fixes in tools/

redfish/computersystem.go, redfish/computersystem_test.go
fields added;
-AutomaticRetryAttempts
-AutomaticRetryConfig
=> expanding the functionality of collecting data about Boot

common/types.go
Fix  json: unsupported type: func(*http.Request) (*url.URL, error)
=> Fix json.Marshal

common/testclient.go, redfish/processor.go, redfish/processor_test.go
[#223](https://github.com/stmcginnis/gofish/issues/233)
=> Fixe tests and string MaxSpeedMHz

redfish/bios.go, redfish/bios_test.go, redfish/computersystem.go, redfish/settings.go
```
{
"@Redfish.Settings": {
"@odata.type": "#Settings.v1_2_2.Settings",
"SettingsObject": {
"@odata.id": "[/redfish/v1/Systems/Self/SD](https://192.168.77.102/redfish/v1/Systems/Self/SD)"
}
},
```
=> Fix system settings

.golangci.yaml, common/entity.go, common/entity_test.go, redfish/manager.go, redfish/network_protocol.go, redfish/network_protocol_test.go
Hi! Thank you very much for this library. I needed support of the NetworkProtocol resource of Manager, so here is my contribution. 
NetworkProtocolSettings struct is based on [this schema](http://redfish.dmtf.org/schemas/v1/ManagerNetworkProtocol.v1_9_1.yaml)
=> Add network protocols support

common/entity.go, common/entity_test.go
Found out that if you update embedded struct field you got wrong payload to patch. Fixing it
=> fixed bug with Update for embedded structs

common/electricalcontext.go, common/physicalcontext.go, redfish/chassis.go, redfish/pcieslots.go, redfish/redundancy.go, redfish/sensor.go, redfish/sensor_test.go
Implemented according to
https://www.dmtf.org/sites/default/files/standards/documents/DSP0268_2023.1.html#sensor-170
=> Add sensors located in the chassis and sub-components. (v1.9+)

redfish/manager.go, redfish/serialinterface.go, redfish/serialinterface_test.go
Implemented according to https://redfish.dmtf.org/schemas/v1/SerialInterface.v1_1_8.yaml
=> Add serial interfaces in manager

redfish/bios.go
=> Allow empty old/new BIOS password

redfish/processor.go
Implemented according to
https://www.dmtf.org/sites/default/files/standards/documents/DSP0268_2023.1.html#processor-1180
=> Add new fields to processor

redfish/power.go, redfish/powerdistribution.go, redfish/powerdistribution_test.go, redfish/powerdistributionmetrics.go, redfish/powerdistributionmetrics_test.go, redfish/powerequipment.go, redfish/powerequipment_test.go, redfish/sensor.go, serviceroot.go
Changes:
- [PowerEquipment](https://www.dmtf.org/sites/default/files/standards/documents/DSP0268_2023.1.html#powerequipment-120)
- [PowerDistribution](https://www.dmtf.org/sites/default/files/standards/documents/DSP0268_2023.1.html#powerdistribution-131) 
- [PowerDistributionMetrics](https://www.dmtf.org/sites/default/files/standards/documents/DSP0268_2023.1.html#powerdistributionmetrics-130)
=> Add power equipment

redfish/networkdevicefunction.go, redfish/networkport.go, redfish/port.go, redfish/port_test.go
https://www.dmtf.org/sites/default/files/standards/documents/DSP0268_2023.2.html#port-1100
=> Add physical port assignment for network device function

redfish/heatermetrics.go, redfish/thermalmetrics.go, redfish/thermalsubsystem.go, redfish/thermalsubsystem_test.go
Some linked objects were not defined right. Fixed that and added unit test coverage based on a real system.
=> Fix references in ThermalSubsystem

redfish/eventservice.go, redfish/eventservice_test.go, redfish/fabric_test.go, redfish/license_test.go, redfish/licenseservice.go, redfish/licenseservice_test.go, redfish/metricdefinition_test.go, redfish/metricreportdefinition.go, redfish/metricreportdefinition_test.go, redfish/sessionservice.go, redfish/sessionservice_test.go, redfish/telemetryservice.go, redfish/telemetryservice_test.go, redfish/triggers_test.go, serviceroot.go, serviceroot_test.go
This contains various improvements based on further testing against a Dell system and the addition of improved test coverage to validate the JSON responses for various objects.
=> Various updates and improved test coverage

redfish/accelerationfunction.go, redfish/addresspool.go, redfish/componentintegrity.go, redfish/ethernetinterface_test.go, redfish/metricdefinition_test.go, redfish/outletgroup.go, redfish/port.go, redfish/settings.go, redfish/volume.go, swordfish/volume.go
=> Fix various spelling errors

redfish/chassis.go, redfish/coolantconnector.go, redfish/coolingunit.go, redfish/leakdetector.go, redfish/pump.go
adds a hodge podge of additions in the 2024.4 DMTF release
=> Add some DMTF 2024.4 release bits

client.go
=> Clean up session on logout

redfish/computersystem.go
In my previous PR(#394) I forgot to actually add the reset type value of `FullPowerCycle`.
=> Fix missing ResetType value

redfish/chassis.go
whoops now realizing that I made a mistake. LeakDetectors is a collection under Chassis 😄
=> LeakDetectors gets the collection in chassis

redfish/computersystem.go
This PR adds Metrics field to MemorySummary object.
ref:
- https://www.dmtf.org/sites/default/files/standards/documents/DSP0268_2025.1.html#processor-1201
- https://www.dmtf.org/sites/default/files/standards/documents/DSP0268_2025.1.html#computersystem-1240
Note:
I see both `Processor` and `ComputerSystem` go types use the same `MemorySummary` type for `MemorySummary` field.
But based on the redfish spec (links above), `MemorySummary` has different properties in both resources:
Processor:
ComputerSystem:
Both have `Metrics` properties, so this PR would be sufficient to me, but if you'd like to change it (introduce go types like `ProcessorMemorySummary` and `ComputerSystemMemorySummary`), I can prepare another PR.
=> Add Metrics to MemorySummary

common/entity.go, redfish/virtualmedia.go, redfish/virtualmedia_test.go
=> redfish/virtualmedia: Return Task if Link present in Insert response

redfish/logservice.go, redfish/logservice_test.go
Adds support for the CollectDiagnosticData action and associated DiagnosticDataDetails info.
=> add support for logservice CollectDiagnosticData

client.go
=> Ensure ClientConfig settings are applied to provided HTTPClients

oem/hpe/thermal.go, redfish/thermal.go, redfish/thermal_test.go
Improved handling of fan and temperature sensors data OEM extensions support for vendor-specific implementations
=> Complete support for Thermal.v1_7_1 schema

redfish/power.go, redfish/power_test.go
added pointers for thresholds as this solves the problem of false triggering of thresholds
=> adaptation to the specification https://redfish.dmtf.org/schemas/v1/Power.v1_7_3.json

redfish/assembly_test.go, redfish/battery_test.go, redfish/batterymetrics_test.go, redfish/circuit_test.go, redfish/control_test.go, redfish/coolantconnector_test.go, redfish/coolingloop_test.go, redfish/environmentmetrics_test.go, redfish/fan_test.go, redfish/heatermetrics_test.go, redfish/leakdetection_test.go, redfish/messageregistry_test.go, redfish/outlet_test.go, redfish/outletgroup_test.go, redfish/power_test.go, redfish/powerdistributionmetrics_test.go, redfish/powersupplyunitmetrics_test.go, redfish/pump_test.go, redfish/reservoir_test.go, redfish/sensor.go, redfish/sensor_test.go, redfish/thermalmetrics_test.go
added pointers for thresholds as this solves the problem of false triggering of thresholds 
added tests that show the problem
=> adaptation to the specification  https://redfish.dmtf.org/schemas/v1/Sensor.v1_11_0.json

common/entity.go, common/entity_test.go, redfish/virtualmedia.go, redfish/virtualmedia_test.go
https://redfish.dmtf.org/schemas/v1/VirtualMedia.v1_6_5.json once again I solved the problem with the fact that there are so-called imaginary data "" which in fact are absent
=> UP to VirtualMedia.v1_6_5.json

redfish/computersystem.go, redfish/computersystem_test.go
Fixes https://github.com/stmcginnis/gofish/issues/455
=> Add AllowableBootSourceOverrideTargetValues + AllowableUefiTargetBootSourceOverrideValues to the Boot object
