stmcginnis/gofish

school/client.go, school/redfish/accounts.go, school/redfish/chassis.go, school/redfish/compositionservice.go, school/redfish/computersystem.go, school/redfish/events.go, school/redfish/hostinterface.go, school/redfish/manager.go, school/redfish/protocol.go, school/redfish/session.go, school/redfish/tasks.go, school/service.go, school/swordfish/datastoragelineofservice.go, school/swordfish/endpointgroup.go, school/swordfish/storageservice.go, school/swordfish/storagesystem.go, tools/source.go
I've also started testing the code against a few different vendors and multiple versions of RedFish to ensure compatibility and also that I won't break anything :).
These changes have been tested against:
// HP Gen10
// Supermicro X10
// Dell M630
// Intel S2600WF0
// Dell M640
The only tricky part for me is to test the swordfish side, because I don't have any device capable a this moment.
----
Adds Actions and create a list of possible ResetType
It's now possible to use the target from Actions to issue a reboot
action. Next step is to work on the boot once action
Update computersystem types to unpack as expected
Dell M640s also require the Accept Header, not only the Content-Type
=> Remove Default.*Path and update ComputerSystem to match the redfish spec

tools/redfish-schema/gen_script.sh, tools/redfish-schema/generate_from_schema.py, tools/redfish-schema/requirements.txt, tools/redfish-schema/source.go
These scripts and source implement an initial pass at importing the Redfish schema directly from dmtf.org.  The output is syntactically correct (except for SerialInterface and Switch), but needs some cleanup to be usable.  The top script (gen_script.sh) is new, the generate_from_schema.py script has had some capabilities added to generate syntactically correct identifiers more frequently, and the source.go file adjusted a bit to make that work.
To generate code:
put all three files into a directory
If needing to import a schema that is NOT 2019.1, adjust the define at the top of the gen_script.sh
>sh ./gen_script.sh
Which will download the schema, use it to determine what objects to import, generate the appropriate next steps, and then execute them, using source.go as a jinja2 template …
=> PR: Redfish import tools

school/redfish/chassis.go, school/redfish/computersystem.go, school/redfish/manager.go, school/redfish/networkadapter.go, school/redfish/networkport.go, school/redfish/processor.go, tools/generate_from_schema.py, tools/source.go
Update the ResetType to match the standard for the library
Move some int to float32 to properly load some responses
Add NetworkAdapters and Networkport
Add extra flag to generate_from_schema.py allowing to switch between swordfish and redfish 
Adds processor.go and make possible to return Processors from ComputerSystem
These changes have been tested against:
// HP Gen10
// Supermicro X10
// Dell M630
// Intel S2600WF0
// Dell M640
// Quanta QuantaGrid D52BM-2U
=> Moar updates :)

school/redfish/computersystem.go
to fix the error
```
FATA[0122] Errors Getting systems from service : json: cannot unmarshal object into Go struct field CSLinks.CooledBy of type string 
FATA[0122] Errors Getting systems from service : json: cannot unmarshal object into Go struct field CSLinks.PoweredBy of type string 
```
=> modify poweredBy and CooledBy to common.link, as they are both links

school/redfish/memory.go
to fix 
```
FATA[0019] Errors Getting memory uri from computer system : json: cannot unmarshal object into Go struct field links.Chassis of type string 
FATA[0011] Errors Getting memory uri from computer system : json: cannot unmarshal object into Go struct field .MemoryLocation of type string
```
=> fix MemoryLocation and Chassis type error

school/redfish/bios.go, school/redfish/computersystem.go, school/redfish/logentry.go, school/redfish/logservice.go, school/redfish/memorydomain.go, school/redfish/networkadapter.go, school/redfish/networkinterface.go, school/redfish/networkport.go, school/redfish/secureboot.go, school/redfish/simplestorage.go
This adds the following objects:
* Bios
* LogEntry
* LogService
* MemoryDomain
* NetworkInterface
* SecureBoot
* SimpleStorage
It also adds access methods for links to these objects from the
ComputerSystem object, as well as other existing objects that did not
have an access method implemented yet.
Closes #19
=> Flesh out ComputerSystem properties and linked objects

school/swordfish/storageservice.go, school/swordfish/storageservice_test.go
Some properties were defined as arrays, but they are actually links to collection objects.
Closes #26
=> Fix StorageService property definitions

school/redfish/power.go, school/redfish/power_test.go, school/redfish/redundancy.go, school/redfish/thermal.go, school/redfish/thermal_test.go
This corrects a few property definitions to make them match the schema.
Closes #28
=> Fix various type errors with Thermal, Redundancy, and Power

school/redfish/power.go
Some objects that are EntityTypes accidentally were changed to be ComplexTypes instead. This adds back the common.Entity inclusion for PowerSupply and Voltage objects.
Closes: #30
=> Fix missing common.Entity in Power objects

README.md, client.go, examples/query_chassis.go, examples/query_sessions.go
This changes the way you connect to a redfish service. ConnectDefault
will use default values to create an unauthenticated connection to the
service (typically useful for testing against the simulator), otherwise
you create a ClientConfig variable that contains all of your connection
settings and pass that in to a Connect call.
Closes: #33
=> Add client connection settings

client.go, redfish/session.go
We observed socket fd leaks related with Session establishment and the Logout function. Over time, repeated session creation and teardown would hold enough fds open to hit default limits.
By ensuring the response body is fully closed we were able to eliminate this issue locally. 
```
COMMAND     PID       USER   FD      TYPE    DEVICE SIZE/OFF      NODE NAME
redfish-e 21798 prometheus  cwd       DIR     253,1      224      1024 /
redfish-e 21798 prometheus  rtd       DIR     253,1      224      1024 /
redfish-e 21798 prometheus  txt       REG     253,1 15085858 235686043 /usr/bin/redfish-exporter
redfish-e 21798 prometheus    0u      CHR       1,3      0t0      1029 /dev/null
redfish-e 21798 prometheus    1w      REG     253,1 24459994  17072230 …
```
=> Ensure response body is closed to prevent fd leak

redfish/bios.go, redfish/bios_test.go
Attributes are a collection of key/value pairs that vary based in implementation. This adds a type and helper methods for the most common value types. The attributes can still be accessed as a map, with direct handling needed for the type of the value.
Closes: #49
=> Add access to Bios Attributes property

client.go
Full trace below. The exporter function that triggered was `Logout()`.
```
Jan 29 11:22:10 prometheus01 redfish_exporter: panic: runtime error: invalid memory address or nil pointer dereference
Jan 29 11:22:10 prometheus01 redfish_exporter: [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x844128]
Jan 29 11:22:10 prometheus01 redfish_exporter: goroutine 1570670 [running]:
Jan 29 11:22:10 prometheus01 redfish_exporter: github.com/stmcginnis/gofish.(*APIClient).Delete(0xc006823f40, 0xc00af972a0, 0x19, 0x872724, 0xc002731d78)
Jan 29 11:22:10 prometheus01 redfish_exporter: /users/sysp/tdockendorf/go/pkg/mod/github.com/treydock/gofish@v0.2.1-0.20200129132656-cfef2fbfcc83/client.go:171 +0x68
Jan 29 11:22:10 prometheus01 redfish_exporter: …
```
=> Avoid nil pointer dereference with errors on Delete

redfish/manager.go
If server returns empty supported reset type, it should be reset without any reset type. Seems like this is the behavior of hpe server
Signed-off-by: Leslie Qi Wang <leslie.qiwa@gmail.com>
=> send reset action if server return empty supported reset type

common/types.go, examples/change_login.go, redfish/accounts.go
Redfish AccountService output does not have Links field. Both Accounts and Roles are contained in the main body.
Would you prefer to keep it this way to prevent confusion with the Accounts() and Roles() methods?
=> Fixed AccountService Links field

redfish/logservice.go, redfish/manager.go
I propose this PR to fix following 2 features.
- Some BMC serve the SEL logs through `Managers/{id}/LogServices`. 
- Posting ClearLog with empty payload occur 'Invalid JSON Format' error.
=> add features for the LogService

client.go, redfish/session.go
Hello Sean,
I've added the possibility of basic authentication against the redfish API. This might be interesting in different scenarios (like the ones for some reason you don't want to have a token).
To the gofish.ClientConfig struct I've added a field called BasicAuth. If not set, it will use the token authentication as before. If set explicitly to true, it will use basic auth. 
To allow this to happen, I've also modified the struct redfish.AuthToken, adding Username, Password and a BasicAuth fields. This will make us be aware if we want to use token auth or basic auth while building the APIClient.
When creating the request for HTTP methods, we will check this struct and we will include the needed headers, either for token auth or basic auth.
Best regards.
/Miguel
=> Added support of basic authentication

redfish/drive_test.go, redfish/memory.go, redfish/memory_test.go, redfish/networkadapter.go, redfish/power.go, redfish/processor.go, redfish/processor_test.go
This fixes an issue with Location and ProcessMetrics fields that were incorrectly defined as strings.
Closes #61
=> Fix unmarshal issues from incorrectly defined fields

common/testclient.go, common/types.go, redfish/accountservice_test.go, redfish/chassis_test.go, redfish/compositionservice_test.go, redfish/computersystem.go, redfish/computersystem_test.go, redfish/drive_test.go, redfish/ethernetinterface_test.go, redfish/eventdestination_test.go, redfish/eventservice_test.go, redfish/hostinterface_test.go, redfish/logservice_test.go, redfish/manager_test.go, redfish/manageraccount_test.go, redfish/memory_test.go, redfish/networkdevicefunction_test.go, redfish/networkport_test.go, redfish/pciedevice_test.go, redfish/power.go, redfish/redundancy_test.go, redfish/secureboot_test.go, redfish/storage_test.go, redfish/thermal.go, redfish/thermal_test.go, redfish/vlannetworkinterface_test.go
This adds a mock Client object that can be used in unit tests to test
calls and adds unit tests to make sure the expected values are sent for
Update() calls.
=> Add unit testing of Update() calls

redfish/chassis.go, redfish/drive.go, redfish/drive_test.go, redfish/memorymetrics.go, redfish/power.go, tools/generate_from_schema.py
The Redfish schema uses the types 'integer' and 'numeric' for field
types. The integer type should be a go int, but numeric types could
contain decimal precision. These fields either need to use float32 or
float64 to handle this.
This updates all redfish objects to use a float type for any that are
defined as numeric in the schema.
=> Update numeric fields to use float

common/types.go
For really old HP/HPE systems, they do not use @odata.id, but use href instead.  This allows the system to continue to limp along and work better.  At least get past session creation.
You may not want this, but it seems to work on my old HP system and continues working with my dell system.
Clicked too quickly on some things.  Edited to add more information.
=> Handle HREF in links but prefer @odata.id

redfish/chassis_test.go
A user of redfish_exporter is getting a failure with one of their
Supermicro servers, but not all. Looking at the raw json returned from
these machines, the failure happens on a host that has a RAID chassis in
addition to the normal system chassis.
The results from getting the RAID chassis don't have as many values as
the full chassis, but according to the required properties defined in
the spec, it does return everything that is required.
To test to see if this was an issue in gofish, added a unit test that
would use the response from this system's RAID chassis and a new test
that validates only the spec-required minimum values. It appears gofish
handles this appropriately, but adding this test just in case. We may
want to add minimum required value tests for more objects, but this is a …
=> Add chassis test for redfish_exporter failure

redfish/session.go
I propose this PR to fix Logout() fail on some vendor and have a question.
According to Redfish specification, client must get the URI of Session Resource from the Location header. But some vendor implementation returns the full URI path like `https://blahblah.blah/redfish/v1/SessionService/Sessions/{session id}`. This URI will generate the invalid session address and fail the logout from BMC, because last runRequest() from the call-path of Logout() combines that full URI path with the endpoint URL. If a user run this as a client tool many times, it makes session overflow.
From that reason I modified the CreateSession, but I didn't put any code to return an error from Logout() on failure.
Is it necessary to return an error when a logout fails?
=> Fix Logout fail

common/types.go, redfish/bios.go, redfish/bios_test.go
This handles the @redfish.Settings value on Bios objects to be able to set attributes.
Closes #80
=> Add ability to set Bios attributes

client.go, common/testclient.go, common/types.go, redfish/eventdestination.go, redfish/session.go
Hello Sean,
I'm proposing the PR in reference to [!82](https://github.com/stmcginnis/gofish/issues/85).
I've little tested the new APIClient.Delete call and it works. I also needed to change some other files that used that call. I've always followed the philosophy of being as less intrusive in the code as possible. 
Now the Client interface looks like this (please check the **Delete** definition):
~~~
type Client interface {
Get(url string) (*http.Response, error)
Post(url string, payload interface{}) (*http.Response, error)
Patch(url string, payload interface{}) (*http.Response, error)
Put(url string, payload interface{}) (*http.Response, error)
Delete(url string) (*http.Response, error)
}
~~~
Files also changed apart from client.go and types.go:
- eventdestination.go
- session.go …
=> Add *http.Response return to APIClient.Delete method

redfish/storage.go, redfish/volume.go
Hello Sean,
I've created this pull request to address something that was missing in the current implementation.
I needed to figure out the *OperationApplyTimeValues* for Storage controllers. This is very useful to see if you can perform a disk operation rightraway (Immediate) or you need to reboot the server (OnReset).
Having these values is highly valuable to see what strategy to follow when it comes to create virtual disks on top of disk controllers 😄 
Let me know!
/Miguel
=> Volume OperationApplyTimeSupport added

redfish/updateservice.go, redfish/updateservice_test.go, serviceroot.go
Hello Sean,
Hope you're doing well 😄 
Recently I've noticed that the gofish API was missing from the *UpdateService* part, which allow operators to update the firmware from their infrastructure.
What I've done is to implement the standard way of upgrading firmware (via **/redfish/v1/UpdateService/Actions/UpdateService.SimpleUpdate**) and left apart the "OEM" functions (which vary from vendor to vendor, i.e. in Dell infra would be **/redfish/v1/UpdateService/Actions/Oem/DellUpdateService.Install**).
This should be portable across vendors.
Also I've added the unit tests needed for the new struct (*UpdateService*) and JSON unmarshalling.
Best regards!
=> Added UpdateService to the API

redfish/eventdestination.go, redfish/eventservice.go, redfish/eventservice_test.go
I had to add Protocol and Context to the payload so Dell would accept
the event subscription definition.
I did that by adding extra arguments all the way through the stack. Since
they are required, I added them before the optional `oem` argument to
those functions.
=> add protocol and context arguments for event subscriptions

redfish/manager.go, redfish/virtualmedia.go, redfish/virtualmedia_test.go
The Manager object has a VirtualMediaCollection link that links to zero
or more VirtualMedia objects. This update adds a call to be able to
retrieve those VirtualMedia objects from a Manager.
=> Add method to get VirtualMedia for a Manager

client.go, go.mod
Some actions require a session token to perform. Rather than require client users to remember credentials and create new clients add a method to clone an existing client and upgrade the security using the stored credentials.
Additionally, some actions (e.g. firmware upload) require a multi-part POST of the firmware to the server. To this end this provides a new function `PostMultipart` that takes and forms a multi-part payload and POSTs it to the requested URL.
Finally, to aide in troubleshooting allow dynamic setting of the client `DumpWriter` to allow targeted request/response tracing and add a `go.mod` file so programs using the library can use a local version easier.
=> Add ability to upgrade client security to session-based and do multi-part POST requests

redfish/messageregistry.go, redfish/messageregistry_test.go, redfish/messageregistryfile.go, redfish/messageregistryfile_test.go, serviceroot.go
This is a proposal of initial work to handle Redfish registries.
It adds 5 new functions in service root:
1) Registries gets the Redfish Registries
2) MessageRegistries gets all the available message registries in all languages
3) MessageRegistriesByLanguage gets the message registries by language.
4) MessageRegistryByLanguage gets a specific message registry by language.
5) MessageByLanguage tries to find and get the message in the correct language from the informed messageID.
These new functions can be useful in a scenario where an application creates event subscriptions and receive events where in the event we have the messageId and the application should discover the details about the event message, like the message, number of args, and others from the available Redfish Registries …
=> Initial work to handle Redfish registries.

.travis.yml, client.go, client_test.go
This proposal adds 2 new functions to do the connection with context:
ConnectContext - The same as Connect, but sets the ctx.
ConnectDefaultContext - The same as ConnectDefault, but sets the ctx.
Because we already have some authentication code inside Connect, the new ConnectContext is not able to reuse Connect with the correct context. So, actually it was required some changes in Connect and ConnectDefault to avoid too much code duplication. 
The context is defined in the client struct to avoid a lot of function/method signature modifications. It is not the preferred Golang idiom to send the context through the functions, but it is still ok in my opinion and it seems other libs do the same approach (probably to avoid to many modifications as would be required here). This could be an …
=> Changes to send the context to the HTTP request.

serviceroot.go
The search for the Redfish message registry by registry/language can be very slow depending on the environment (existing number of registries / size of the registries). 
Created new function to get the MessageRegistry directly from an uri, avoiding doing unecessary searches to find it.
=> Adding a more simple and performatic function to get a redfish message registry.

redfish/computersystem.go
This property is actually an object that contains properties that link
to other services. The existing definition as a string is not correct,
so even though we don't have full support for it yet, at least mark it
private so that marshalling does not have problems if a host returns the
correct data structure.
Closes: #109
=> Hide ComputerSystem.HostedServices property for now

redfish/manageraccount.go
Working with user management I found that the etag was needed when doing Patches to user accounts.
=> Add etag to ManagerAccount

client.go, client_test.go, common/types.go
Hi Sean,
Working in our Terraform project, I found very useful that when the Redfish API returns also a 404, the client returns an Error struct rather than a generic error. That will allow us to actually distinguish between an actual error or a simple "doesn't exist".
I'm sending this PR to meet this specific case. I need to find out if the GetVolume() function below actually fails or returns 404.
~~~
v, err := redfish.GetVolume(c, "/redfish/v1/Systems/System.Embedded.1/Storage/RAID.Integrated.1-1/Volumes/Disk.Virtual.0:RAID.Integrated.1-1")
if val, ok := err.(*common.Error); !ok {
panic(err)
}
~~~
Please let me know.
Best regards!
/Miguel
=> Return Error struct also for 404

.github/workflows/check.yml, .travis.yml
This drops TravisCI in favor of just using GitHub Actions for PR testing needs.
=> Switch to GitHub Actions for CI

common/testclient.go
Hi Sean,
Just pushing this PR to update **TestClient** struct to be as similar as possible to **APIClient** struct (considering recent changes on **APIClient** regarding the returned Error struct).
Let me know 😄 
Best regards!
/Miguel
=> TestClient updated according APIClient

.github/workflows/check.yml
Mainline branch was renamed from master to main. Check job needs to be updated to run on the new branch name.
=> Update check jobs to trigger on main

redfish/virtualmedia.go, redfish/virtualmedia_test.go
Hello Sean,
Sorry I had to open another pull request. I've reset the two commits I had in my repo that implemented the old solution.
As we agreed, I've created a new exportable (public) struct called *VirtualMediaConfig* that can be passed to the new method *InsertMediaConfig*. Unfortunately Go doesn't support method overloading so another name had to be used. I think that method name should be ok. Tests were implemented as well.
Also I've kept what I did in the previous implementation regarding EjectMedia and avoiding sending no body at all, just sending an empty JSON object to avoid issues with different Redfish implementations.
Let me know 😄 
Best regards!
/Miguel
=> Added VirtualMediaConfig struct and new method

redfish/softwareinventory.go, redfish/softwareinventory_test.go, redfish/updateservice.go
This PR adds ability to list firmware and software inventories from Redfish updateService.
More details here: https://github.com/stmcginnis/gofish/pull/106/files#r573121773
@stmcginnis  I noted there is a script to help to generate the objects from the Redfish schema "gen_script.sh", very nice. 
This time I used the script to generate softwareinventory.go. Just cleared a little bit the generated file to have only some basic initial functionalities. Also, changed somethings in the generated file, for example the Oem type to be an interface{} We can fix this in the script later.
I copied the test file "softwareinventory_test.go" from @DanDanN00dle PR (https://github.com/stmcginnis/gofish/pull/106) and the tests are passing.
Also, I did a test with a real Redfish server and I was able to …
=> Adding ability to list firmware and software inventories from Redfish UpdateService.

redfish/computersystem.go
The ManagedBy property  of ComputerSystem is not exposed
in the main struct, the property  is available since v1.0.0
see [1]
[1] http://redfish.dmtf.org/schemas/v1/ComputerSystem.1.0.0.json
=> Expose ManagedBy property  in ComputerSystem

redfish/computersystem_test.go
If Marshal and Unmarshal are executed in a CS struct
with ManagedBy set, the struct after Unmarshal will
have an empty ManagedBy list. This commit fix this
problem and add tests to cover this scenario.
=> Fix ManagedBy in ComputerSystem

common/testclient.go, common/types.go
Hi Sean,
In my previous PR I forgot to update the Client interface as well as the TestClient to accomodate new methods (XXXWithHeaders as well as Multipart ones).
Maybe in the future, before 1.0 release we can re-design the client interface as well as the APIClient to just have another argument for customHeaders in get/post/put/patch/delete😄 .
Let me know!
/Miguel
=> Client interface and TestClient updated

client.go
This cleans up some of the duplication in code in the client and removes
some commented out code that is no longer needed.
=> Clean up client calls

common/types.go, redfish/manageraccount_test.go
There are several read/write fields that have different property names
to conform to go standards than their json names. A common one being
something like RoleID (go) versus RoleId (json).
This updates the common Update logic account for the names being
different so we don't try to update a field that the system will not
recognize.
Closes: #124
=> Handle json name being different than property name

redfish/chassis.go, redfish/chassis_test.go, tools/gen_script.sh
This adds the ability to get the drives associated with a Chassis object.
Also includes a few small cleanups.
=> Add Chassis Drives linkage

redfish/chassis.go
Accidentally left some logging for the drive information in Chassis.
Closes: #143
=> Remove debug print statement from Chassis

redfish/manager.go, redfish/manager_test.go
Hi Sean,
I need to use oem, oemLinks and OemActions on my Terraform provider. I did the same as the simpleUpdate for the plugin system.
Changed oem and oemLinks from map[string]interface{} to json.RawMessage, so everyone can build structs around it and parse that stuff accordingly.
Also I added an OemActions field, so OemActions can be parsed later as well.
Let me know!
Best regards.
/Miguel
=> Manager set to plugin system

common/types.go, swordfish/spareresourceset_test.go
Request updating package `common`'s `PostalAddress` struct to make `Country` a `string` instead of an `int`.
It appears, from the comments, as if the current rationale for making this an integer value (reference to RF5139) is incorrect. Per  [RFC5139](https://datatracker.ietf.org/doc/html/rfc5139#section-3.3)
**3.3.  Country Element**
The "country" element differs from that defined in [RFC4119] in that
it now restricts the value space of the element to two uppercase
characters, which correspond to the alpha-2 codes in [ISO.3166-1].
**3.4.  A1 Element**
The "A1" element is used for the top-level subdivision within a
country.  In the absence of a country-specific guide on how to use
the A-series of elements, the second part of the ISO 3166-2 code
[ISO.3166-2] for a country subdivision …
=> Update types.go -- make PostalAddress.Country a string

redfish/manager.go
HostInterfaces is one property based on Manager.v1_12_0 (maybe
earlier version too)
Signed-off-by: Leslie Qi Wang <qiwa@pensando.io>
=> add HostInterfaces implementation on Manager object

.github/workflows/check.yml, client.go, common/testclient.go, go.mod, redfish/chassis_test.go, redfish/eventservice_test.go, redfish/session_test.go
This version pulls in some updated linters with better checks and
version support. Some linters had an issue when running under go 1.17.
This also raises the declared go version to 1.16 to pick up the
deprecation of ioutils.
=> Bump golangci-lint to 1.43.0

redfish/ethernetinterface_test.go, redfish/ipaddresses.go
range of prefix length of ipv6 address should be 1-128.
Signed-off-by: Leslie Qi Wang <leslie.qiwa@gmail.com>
=> fix type of prefix length of ipv6 address

redfish/updateservice.go
This field enables clients to determine if the updateservice supports Multipart push updates.
_A service may support the `MultipartHttpPushUri` property within the
UpdateService resource. A client can perform an HTTP or HTTPS POST request on the URI specified by this property to initiate a push-based update._
https://www.dmtf.org/sites/default/files/standards/documents/DSP2062_1.0.0.pdf
=> redfish/updateservice: struct field MultipartHTTPPushURI

client.go
To enable clients to submit their own multipart payload,
it would help to export the `runRawRequestWithHeaders` method.
In my case, the multipart form-data needed to be in the following format,
which isn't directly supported within the `runRequestWithMultipartPayloadWithHeaders` 
method, and needed more work to prepare the first part of the MIME header.
```
Content-Length: 416
Content-Type: multipart/form-data; boundary=--------------------
----1771f60800cb2801
--------------------------1771f60800cb2801
Content-Disposition: form-data; name="UpdateParameters"
Content-Type: application/json
{"Targets": [], "@Redfish.OperationApplyTime": "OnReset", "Oem":
{}}
--------------------------1771f60800cb2801
Content-Disposition: form-data; name="UpdateFile"; filename="dum
myfile"
Content-Type: …
```
=> client: export method runRawRequestWithHeaders

client.go, client_test.go
This enables callers to write testable interfaces instead of directly accessing fields on the APIClient.
For example
```go
// defined in a caller's package
type RedfishClient interface {
GetService() *Service
Logout()
}
type MyType struct {
client RedfishClient 
}
func NewMyType(endpoint string) (*MyType, error) {
r := &MyType{}
var err error
r.client, err = gofish.ConnectDefault(endpoint)
if err != nil {
return nil, err
}
return r, nil
)
func main(){
mt, _ := NewMyType("")
fmt.Println(mt.client.GetService().Systems()[0].BIOSVersion)
mt.client.Logout()
}
```
Signed-off-by: Micah Hausler <mhausler@amazon.com>
=> Add GetService() method to APIClient

redfish/bios.go
In many cases. I think that if `UpdateBiosAttributes`  function can pass apply time is easy to use .
this case is convert from the DELL bios setting
```shell
RACADM set bios.SysProfileSettings.SysProfile PerfPerWattOptimizedOs
RACADM jobqueue create BIOS.Setup.1-1
```
to set the logger to show the http request of setting as follow
```go
type PrintHttp2OutputWrite struct {
}
func (p *PrintHttp2OutputWrite) Write(b []byte) (n int, err error) {
return fmt.Printf("%s", string(b))
}
```
and set the Write to gofish config
```go
config := gofish.ClientConfig{
...
DumpWriter: PrintOut,
}
```
```log
PATCH /redfish/v1/Systems/System.Embedded.1/Bios/Settings HTTP/1.1
Host: 192.168.156.16
User-Agent: gofish/1.0
Connection: close
Content-Length: 91
Accept: application/json
Content-Type: …
```
=> feature: support pass apply time when set BIOS Attr

redfish/bios.go, redfish/bios_test.go
This refactors the code slightly to reduce duplication and adds a basic
unit test to cover the case of providing an apply time to the BIOS
update.
=> Clean up and testing for UpdateBiosAttributesApplyAt

redfish/bios.go
the user can update the huawei machine boot order by set the arrt of bios.
```json
PATCH /redfish/v1/Systems/1/Bios/Settings HTTP/1.1
Host: 192.168.142.53
User-Agent: gofish/1.0
Connection: close
Content-Length: 129
Accept: application/json
Content-Type: application/json
Cookie: sessionKey=xxx
If-Match: W/"8052ea0b"
X-Auth-Token: xx
Accept-Encoding: gzip
{"Attributes":{"BootTypeOrder0":"Others","BootTypeOrder1":"PXE","BootTypeOrder2":"DVDROMDrive","BootTypeOrder3":"HardDiskDrive"}}
HTTP/1.1 200 OK
Connection: close
Content-Length: 624
Cache-Control: max-age=0, no-cache, no-store, must-revalidate
Content-Security-Policy: default-src 'none'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; connect-src 'self' wss://*:*; img-src 'self' data:; frame-src 'self'; font-src 'self' data:; …
```
=> feature: support huawei machine set bootorder

redfish/chassis.go, redfish/computersystem.go
This needs to be addressed library-wide yet, but as a proof of concept
this adds eTag awareness just to the ComputerSystem object. This is used
when making updates to ensure the object has not changed underneath us
which could potentially cause problems by making updates based on stale
information.
Closes: #171
=> Add etag support to ComputerSystem

.github/workflows/check.yml, client.go, client_test.go, common/types.go, oem/dell/eventservice_test.go, oem/zt/eventservice_test.go, redfish/chassis_test.go, redfish/computersystem.go, redfish/computersystem_test.go, redfish/eventservice_test.go, redfish/logservice_test.go, redfish/memory_test.go, redfish/messageregistry.go, redfish/messageregistry_test.go, redfish/networkdevicefunction_test.go, redfish/pciedevice_test.go, redfish/power.go, redfish/redundancy_test.go, redfish/secureboot_test.go, redfish/vlannetworkinterface_test.go, serviceroot.go, swordfish/endpointgroup_test.go, swordfish/ioperformanceloscapabilities_test.go, swordfish/spareresourceset_test.go, swordfish/storagepool_test.go
The newer releases of golangci-lint have had issues as they try to work
through changes in go 1.19 while keeping backward compatibility. In the
meantime, this pins to an older version and bumps up the version of go
used in CI.
Also some minor cleanup on nolint tags.
=> Pin golangci-lint to avoid go conflicts

.github/workflows/check.yml, .golangci.yaml, redfish/messageregistry.go, serviceroot.go
This version pulls in some updated linters with better checks and
version support.
=> Bump golangci-lint to 1.49.0

tools/gen_script.sh, tools/generate_from_schema.py, tools/source.tmpl
Fixed formatting issues (double spaces, excessive newlines, const names) in template output; fixed directory issues and cleaned up code in gen_script.sh; switched to int-based schema version selection and `re` for code cleanup, minor fixes in generate_from_schema.py.
=> Various fixes in tools/ to improve code generation

redfish/memory.go
With the change to make memory fetch async in
0b4ea564cb6065f0caec27ee9b90a64d4f36b096 there was a `//nolint:dupl` that is no longer needed. This just drops that linter flag.
=> Fix lint issue with nolint:dupl no longer needed

.github/workflows/check.yml
This updates the `checkout`, `setup-go`, and `golangci-lint` versions to v3 to use the latest. Deprecation warnings have started to be logged for the v2 version of `golangci-lint`, so we should get up to date to avoid any issues there.
=> Update GitHub Action versions

redfish/memory.go
this pull request fix the [204](https://github.com/stmcginnis/gofish/pull/204) adding the wg.Add(1) in the for loop and fix the collectionError
=> Fix get memeories async

redfish/virtualmedia.go
The redfish implementation of Supermicro doesn't seem to like `Inserted` or `WriteProtected` as additional properties for the InsertMedia action target and rejects requests which include them:
```
{
"error": {
"code": "Base.v1_4_0.GeneralError",
"Message": "A general error has occurred. See ExtendedInfo for more information.",
"@Message.ExtendedInfo": [
{
"MessageId": "Base.1.4.PropertyUnknown",
"Severity": "Warning",
"Resolution": "Remove the unknown property from the request body and resubmit the request if the operation failed.",
"Message": "The property Inserted is not in the list of valid properties for the resource.",
"MessageArgs": [
"Inserted"
],
"RelatedProperties": [
"Inserted"
]
},
{
"MessageId": "Base.1.4.PropertyUnknown",
"Severity": "Warning",
"Resolution": "Remove the …
```
=> Fix VirtualMediaConfig for Supermicro

client.go
The panic occurs if a caller of APIClient attempts to run GetSession() when APIClient.auth has not yet been set.
=> client.go: fixes a panic when the client.auth is nil

common/collection.go, common/types.go
some dell machine not provider the `Members@odata.count` field
```
curl https://192.168.156.212/redfish/v1/Managers/iDRAC.Embedded.1 -u username:passwd --insecure -k --ciphers DEFAULT@SECLEVEL=1 | jq|grep FirmwareVersion
...
"FirmwareVersion": "2.30.30.30",
```
so the system info as follow
```json
{
"@odata.context": "/redfish/v1/$metadata#Systems",
"@odata.count": 1,
"@odata.id": "/redfish/v1/Systems",
"@odata.type": "#ComputerSystem.1.0.0.ComputerSystemCollection",
"Description": "Collection of Computer Systems",
"Members": [
{
"@odata.id": "/redfish/v1/Systems/System.Embedded.1"
}
],
"Name": "Computer System Collection"
}
```
and you can to compare with the stand format response( this body copy from another machine)
```json
{
"@odata.context": …
```
=> bugfix: some dell machine /redfish/v1/systems without memeber@count

redfish/thermal.go
the SensorNumber of Temperatures need change the type from `int` to `float32`
```json
{
"@odata.context": "/redfish/v1/$metadata#Chassis/Members/1/Thermal/$entity",
"@odata.id": "/redfish/v1/Chassis/1/Thermal",
"@odata.type": "#Thermal.v1_2_0.Thermal",
"Id": "Thermal",
"Name": "Thermal",
"Status": {
"Oem": {
"Huawei": {
"Severity": "Informational"
}
},
"HealthRollup": "OK"
},
"Oem": {
"Huawei": {
"FanSpeedAdjustmentMode": "Automatic",
"FanSpeedLevelPercents": 10.0,
"FanManualModeTimeoutSeconds": 100.0,
"FanSpeedMinimalLevelPercents": 10,
"FanSpeedMaximumLevelPercents": 100,
"FanTotalPowerWatts": 17.710000000000001,
"TemperatureSummary": {
"Count": 22,
"Status": {
"Severity": "Informational",
"HealthRollup": "OK"
}
},
"FanSummary": {
"Count": 7,
"Status": {
"Severity": "Informational", …
```
=> bugfix: fix type of SensorNumber

redfish/storage.go
update the data type of SpeedGbps
```json
{
"@odata.context": "/redfish/v1/$metadata#Systems/Members/1/Storages/Members/$entity",
"@odata.id": "/redfish/v1/Systems/1/Storages/RAIDStorage0",
"@odata.type": "#Storage.v1_7_0.Storage",
"Id": "RAIDStorage0",
"Name": "RAIDStorage0",
"StorageControllers@odata.count": 1,
"StorageControllers": [
{
"MemberId": "0",
"@odata.id": "/redfish/v1/Systems/1/Storages/RAIDStorage0#/StorageControllers/0",
"@odata.type": "#Storage.v1_7_0.StorageController",
"Name": "RAID Card1 Controller",
"Description": "RAID Controller",
"Status": {
"State": "Enabled",
"Oem": {
"Huawei": {
"FaultDetails": null
}
},
"Health": "OK"
},
"SpeedGbps": 12.0,
"FirmwareVersion": "5.030.00-1512",
"SupportedDeviceProtocols": [
"SAS"
],
"SerialNumber": "024JMY6TJB005180", …
```
=> bugfix: fix SpeedGbps type with float32

redfish/taskervice.go, redfish/taskervice_test.go, serviceroot.go
```
"Product": "AMI Redfish Server"
"Tasks": {
"@odata.id": "[/redfish/v1/TaskService](https://ip/redfish/v1/TaskService)"
},
{
"@odata.context":"/redfish/v1/$metadata#TaskService.TaskService",
"@odata.etag":"\"1614826331\"",
"@odata.id":"/redfish/v1/TaskService",
"@odata.type":"#TaskService.v1_1_4.TaskService",
"CompletedTaskOverWritePolicy":"Oldest",
"DateTime":"2022-10-10T00:04:51-05:00",
"Description":"Task Service",
"Id":"TaskService",
"LifeCycleEventOnTaskStateChange":true,
"Name":"Task Service",
"ServiceEnabled":true,
"Status":{
"Health":"OK",
"State":"Enabled"
},
"Tasks":{
"@odata.id":"/redfish/v1/TaskService/Tasks"
}
}
```
=> feat: Add task service support

redfish/taskervice.go, redfish/taskervice_test.go
Handling was causes failures in other tests. Clean things up to the simpler format used for most other objects.
Also removes `rawData` since this object does not have any update methods, so no reason to keep that data stored in memory.
=> Clean up TaskService testing

redfish/processor.go, redfish/processor_test.go
faced with a device that is implemented according to the specification "#Processor.v1_5_1.Processor"
and the library did not properly process it
ex: 
`{
"@odata.context": "/redfish/v1/$metadata#Processor.Processor",
"@odata.etag": "\"1677574563\"",
"@odata.id": "/redfish/v1/Systems/Self/Processors/CPU_1",
"@odata.type": "#Processor.v1_5_1.Processor",
"Id": "CPU_1",
"Links": {
"Chassis": {
"@odata.id": "/redfish/v1/Chassis/Self"
},
"ConnectedProcessors": [
{
"@odata.id": "/redfish/v1/Systems/Self/Processors/CPU_1/SubProcessors/CPU_1_Core13"
},
{
"@odata.id": "/redfish/v1/Systems/Self/Processors/CPU_1/SubProcessors/CPU_1_Core15"
},
{
"@odata.id": "/redfish/v1/Systems/Self/Processors/CPU_1/SubProcessors/CPU_1_Core14"
},
{
"@odata.id": …
=> correct processing sub processor

client.go, client_test.go
Our test bmc have problem with parallel requests
random uri with error
`failed to retrieve some items: [{"link":"/redfish/v1/Systems/Self/EthernetInterfaces/EthernetInterface0","error":"403: \u003c?xml version=\"1.0\" encoding=\"iso-8859-1\"?\u003e\n\u003c!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\"\n         \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\"\u003e\n\u003chtml xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\" lang=\"en\"\u003e\n \u003chead\u003e\n  \u003ctitle\u003e403 - Forbidden\u003c/title\u003e\n \u003c/head\u003e\n \u003cbody\u003e\n  \u003ch1\u003e403 - Forbidden\u003c/h1\u003e\n \u003c/body\u003e\n\u003c/html\u003e\n"},{"link":"/redfish/v1/Systems/Self/EthernetInterfaces/EthernetInterface1","error":"403: \u003c?xml version=\"1.0\" …
=> fix: add mutex to http client

redfish/eventdestination.go, redfish/eventservice.go, redfish/eventservice_test.go
I'd like to suggest some changes for EventService subscriptions
According to [Redfish documentation](https://www.dmtf.org/sites/default/files/standards/documents/DSP2046_2022.2.pdf) p.6.34.3
> For the possible property values, see EventTypes in Property details. Deprecated in v1.5 and later. This property has been deprecated. Starting with Redfish Specification v1.6 (Event v1.3), subscriptions are based on the RegistryPrefix and ResourceType properties and not on the EventType property.
Now there's the following error when subscribing to events (Redfish v.1.5+, here: Redfish v.1.15.1):
`400: {"error":{"@Message.ExtendedInfo":[{"@odata.type":"#Message.v1_0_8.Message","Message":"The property EventTypes is not in the list of valid properties for the …
=> Update event subscription for Redfish v.1.5+

common/collection.go, redfish/pciedevice.go, redfish/pciedevice_test.go
standard : https://www.dmtf.org/sites/default/files/standards/documents/DSP2046_2019.2.pdf
example:
**{
"@odata.id": "/redfish/v1/Systems/system/PCIeDevices/S0B101D0",
"@odata.type": "#PCIeDevice.v1_4_0.PCIeDevice",
"DeviceType": "MultiFunction",
"Id": "S0B101D0",
"Manufacturer": "QLogic Corp.",
"Model": "ISP2722-based 16/32Gb Fibre Channel to PCIe Adapter (QLE2742 Dual Port 32Gb Fibre Channel to PCIe Adapter)",
"Name": "PCIe Device",
"PCIeFunctions": {
"@odata.id": "/redfish/v1/Systems/system/PCIeDevices/S0B101D0/PCIeFunctions"
}
}**
=> according to the 1.4 PCIeFunctions standard has been moved

.github/workflows/check.yml, common/collection.go, redfish/chassis.go
This update golangci-lint to the current latest version and updates Go to 1.20.2 when used in the GitHub Action workflow.
=> Update golangci-lint and go versions

.golangci.yaml
This linter setting is really too low for some things. Raise it up higher so it doesn't cause unnecessary work refactoring methods.
=> Raise gollangci-lint cyclometric complexity

client.go, client_test.go, go.mod
This allows the concurrency of HTTP client to be configured (it is 1 by default in order to maintain the existing behaviour). This also has the added benefit that a context cancellation will abort the lock acquisition
=> make concurrency configurable

redfish/task.go, redfish/task_test.go
According to the [Redfish Firmware Update White Paper](https://www.dmtf.org/sites/default/files/standards/documents/DSP2062_1.0.0.pdf) (section 6.3), tasks can transition to a job, and the job URI is provided via the task message args. So we need to be able to fully decode task messages.
=> Decode task messages

redfish/computersystem.go
Added virtual media as part of ComputerSystem along with getter method.
Redfish URI to get virtual media: `redfish/v1/Systems/{system ID}/VirtualMedia`
=> Support for VirtualMedia under ComputerSystem

redfish/volume.go
Adding `ReadCachePolicy` and `WriteCachePolicy` under redfish volume.
=> Adding read, write cache policy to redfish volume

redfish/bios.go
ResetBios fails with a nil payload. An empty payload is accepted.
=> fix: Pass payload during bios reset

redfish/job.go, redfish/job_test.go, redfish/jobservice.go, redfish/jobservice_test.go, serviceroot.go
Alternative to #257 (abandoned?) that addresses issues noted in that PR:
* Rename `ServiceCapabilities` to `JobServiceCapabilities` (consistent with schema)
* Rename service capability `ServiceEnabled` to `Scheduling` (consistent with schema. `ServiceEnabled` is a property of `JobService` rather than a capability)
* export `ListReferencedJobs` (consistent with other gofish library services)
* Move `GetJob` and `ListReferencedJobs` from jobservice.go to job.go (consistent with other gofish library services)
=> Add jobservice and job types

redfish/computersystem.go, redfish/computersystem_test.go
This flag allows to override UEFI HTTP Boot URI, only works when BootSourceOverrideTarget is set to UefiHttp.
I could not find any unit test for updating boot structure, let me know if I missed it. Thanks!
=> Add HttpBootUri into Boot

common/entity.go
While using this client with Intel machines, we came across an issue where PATCH and POST requests were failing due to unmatched etags.
Some vendors surround header etag with quotes, which need to be cleaned before sending a patch.
This MR simply adds an option to trim quotes from the etag before it is added to the header of the request
=> Add option to clean etag before PATCH and POST

common/entity.go
This is a work around for (crappy) vendor implementations where the `If-Match` header does not work - even with '*' as the value, requests are incorrectly denied with an ETag mismatch error.
=> common/entity: adds parameter to skip the If-Match Etag header

redfish/manager.go, redfish/manager_test.go
Sometimes Manager.Reset action doesn't provide AllowableValues for ResetTypes, like that:
```
"Actions": {
"#Manager.Reset": {
"target": "/redfish/v1/Managers/1/Actions/Manager.Reset/"
}
}
```
In this case current implementation provides a payload `{"Action": "Manager.Reset"}` which doesn't work at least for HP gen9 (iLO4) that I can test on. I get `Base.0.10.ActionNotSupported` error.
According to the [specification](https://redfish.dmtf.org/schemas/v1/Manager.v1_18_0.yaml):
```
Manager_v1_18_0_ResetRequestBody:
....
ResetType:
...
x-longDescription: This parameter shall contain the type of reset.  The
service can accept a request without the parameter and perform an implementation
specific default reset.  Services should include the @Redfish.AllowableValues
annotation for this parameter …
```
=> fix manager reset action when no allowed values for reset type are provided

serviceroot.go
Use the `redfish.GetTaskService()` method to retrieve linked Task objects instead - since they cannot be unmarshaled by common.Client.
=> Services.Tasks(): fix no Task objects being returned

redfish/computersystem.go, redfish/powerdistribution.go, redfish/powersupplyunit.go, redfish/powersupplyunit_test.go, redfish/powersupplyunitmetrics.go, redfish/powersupplyunitmetrics_test.go
Changes:
- [power supply](https://www.dmtf.org/sites/default/files/standards/documents/DSP0268_2023.1.html#powersupply-151)
- [power supply metrics](https://www.dmtf.org/sites/default/files/standards/documents/DSP0268_2023.1.html#powersupplymetrics-110)
=> Add power supplies

redfish/updateservice.go, redfish/updateservice_test.go
as defined in the spec 
https://www.dmtf.org/sites/default/files/standards/documents/DSP0268_2023.1.html#updateservice-1113
=> updateservice: add the StartUpdate target

redfish/task.go, redfish/task_test.go
This exposes the Task `Oem` field to the caller, its upto the caller to unmarshal its contents.
@stmcginnis  Let me know if this should go into `common.Entity` or if it should be done differently.
=> redfish/task: Adds the Oem field as json.RawMessage

redfish/virtualmedia.go, redfish/virtualmedia_test.go
we need to add a new parameter because without it an error occurs:
400: {
"MediaType@Message.ExtendedInfo": [
{
"@odata.type": "#Message.v1_1_1.Message",
"Message": "The property MediaType is a required property and must be included in the request.",
"MessageArgs": [
"MediaType"
],
"MessageId": "Base.1.8.1.PropertyMissing",
"MessageSeverity": "Warning",
"Resolution": "Ensure that the property is in the request body and has a valid value and resubmit the request if the operation failed."
}
]
}
=> added new parameter MediaType to VirtualMediaConfig

client.go
I caught a panic in a pet project on the state switch when I checked if the connection was available and if the. bmc's service was available
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x138a3ae]
goroutine 1 [running]:
github.com/stmcginnis/gofish.(*APIClient).Logout(0x0?)
/Users/max/Desktop/code/device-mgr/vendor/github.com/stmcginnis/gofish/client.go:576 +0xe
panic({0x13e4040?, 0x1812cf0?})
=> fix insurance, check that the object is still active before disconnecting

redfish/chassis.go
=> Add LocationIndicatorActive as a field in chassis

redfish/accountservice.go
This adds the ability to create basic user accounts via a method call on the AccountService. It does not currently handle things like ActiveDirectory or LDAP integration.
Closes: #72
=> Add ability to create user accounts

redfish/accountservice.go, redfish/accountservice_test.go
Some things were missed in the last update of the AccountService to the current (2023.3) spec. This adds those missing pieces and updates the unit test mockup to reflect the changes.
=> Update AccountService object

redfish/chassis.go
With the recent update to the 2023.3 bundle, there were a few properties and linked objects that were missed in the chassis object. This adds most of them.
=> Update Chassis missing properties

redfish/ethernetinterface.go, redfish/ethernetinterface_test.go, redfish/resourceblock_test.go, redfish/zone_test.go
Add unit test coverage to more objects.
Also adds access to deprecated EthernetInterface.VLANs property since this is still in use by many systems.
=> Unit test improvements

redfish/computersystem.go, redfish/computersystem_test.go
This was incorrectly defined as a string. It's actually a link to a collection to get the associated USB devices, so parsing the object would fail on systems with USB present.
=> Fix ComputerSystem USBControllers property

redfish/thermal.go, redfish/thermal_test.go
Fans and Temperature objects have a RelatedItem field that is actually an array of links. Switch over to extracting the links, though not exposing the URIs yet.
=> Fix marshalling error with Thermal objects

redfish/computersystem.go, redfish/computersystem_test.go
This is an array of links to Managers. We had been just collecting the strings for the URIs, but to make this consistent with how other related objects are handled this makes the objects themselves accessible by a method call.
=> Fix ComputerSystem.ManagedBy access

redfish/networkadapter.go
This changes a number of properties of the `NetworkAdapter` resource type (`NetworkPorts`, `Ports`, `Processors`, etc.) to be parsed as `common.Link` instead of `common.LinksCollection`. Meaning that each of these properties will now be parsed a single link to a collection resource rather than as an array of links.
(For `NetworkDeviceFunctions` and `NetworkPorts`, the flip from `common.LinksCollection` to `common.Link` reverses the change that occurred in https://github.com/stmcginnis/gofish/commit/646d2abd848f96887a93d47e5d148294664e6572. The other properties were newly added to gofish.)
This is necessary for`NewtworkAdapter` to parse correctly. Please correct me if I'm somehow confused here, but the spec for the latest `NetworkAdapter` schema …
=> Swtich NetworkAdapter fields from common.LinksCollection to common.Link

redfish/chassis.go
Missing the method call to retrieve the associated PowerSubsystem for a Chassis object.
=> Add Chassis PowerSubsystem access

redfish/powersubsystem.go, redfish/powersubsystem_test.go
Their implmentation incorrectly returns PowerSubsystem.Attributes as an array, causing unmarshal errors. This works around that by skipping it.
=> Workaround for NVIDIA PowerSubsystem issue

redfish/manager.go, redfish/manager_test.go
Links to associated ports were not defined correctly.
=> Fix collection links in Manager object

redfish/storage.go, redfish/storage_test.go, redfish/storagecontrollermetrics.go
A few more things that are actually single links to a collection, rather than a collection of links.
=> Fix Storage linked collections

redfish/pciedevice.go, redfish/pciefunction.go
Some vendors include useful information in their OEM information for these objects. Make it possible to access this data.
=> Expose OEM information for PCIeDevice and PCIeFunction

redfish/license.go
The `AuthorizedDevices` property was not defined correctly.
=> Fix License object marshalling issue

redfish/outlet.go, redfish/outlet_test.go
The PowerState property is the common PowerState enum, but the action call for PowerControl needs to use the more limited ActionPowerState that only includes the valid power control request state.
Closes: #339
=> Fix Output.PowerControl PowerState argument type

redfish/logservice.go
Starting with the 1.3.0 schema, the ClearLog call expects to have the etag of the LogEntryCollection as an argument.
This adds a retry to make sure we cover both the pre-1.3 and post-1.3 methods.
=> Handle LogService v1.3.0 ClearLog payload

redfish/computersystem.go
I'd like to add `ComputerSystem.OEM` field as HPE and Dell provide it.
It's not part of the Redfish API schema so not sure if this is the right way to do it.
=> Add OEM field for ComputerSystem

redfish/hostinterface.go
Attempted use of Hostinterface (ie `redfish.GetHostInterface(c, uri)`) led to error:
```
json: cannot unmarshal object into Go struct field .CredentialBootstrapping of type string
```
The CredentialBootstrapping variable may have intended to be of type "CredentialBootstrapping" (struct defined earlier), which was not referenced elsewhere in gofish.
This commit resolves the unmarshal issue.
=> r/hostinterface.go: Correct "CredentialBootstrapping" type

client.go
This adds a `ReuseConnections` configuration flag. When set, this will try to configure the HTTPClient transport to not immediately close connections so that they can be reused by subsequent API calls.
Closes: #349 
I ran something that collects a lot of different information from a system. Its original unmodified timing was:
```txt
real	0m35.706s
user	0m0.165s
sys	0m0.063s
```
After setting the new reuse flag, the same operations timing was:
```txt
real	0m26.284s
user	0m0.266s
sys	0m0.083s
```
I also tried tweaking both `ReuseConnections: true` and `MaxConcurrentRequests: 2` and got even better results:
```txt
real	0m21.510s
user	0m0.092s
sys	0m0.039s
```
=> Expose config option to keep alive TCP connections

.github/workflows/check.yml, go.mod
There have apparently been some bug fixes related to generics in recent releases. This causes problems when using Gofish with older Go releases where it does not like the contraints defined on some of the recent updates using generics. This raises our minimum to 1.21 as this is a version known to work.
While I would have liked to keep the minimum version older to give more flexibility to library consumers, there are multiple good reasons to update to the newer release. I do feel bad about the very short notice though.
=> Raise minimum Go version to 1.21

redfish/power.go
This change makes it so we can access the `RedundancySet` param, which contains all actual Power Supplies vs what is listed in `.PowerSupplies` as that can contain anything in the PSU slots, which sometimes are fans and not actual power supplies.
=> Add ability to get the RedundancySet for a given Redundancy group in the Power resource

.github/workflows/check.yml, Makefile
This updates the version of golangci-lint used in linting to the current latest release of 1.59.1.
=> Update golangci-lint to 1.59.1

redfish/memory.go
Since Redfish DMTF Data Spec 2022.2 the Memory field `NonVolatileSizeLimitMiB` is supposed to be type `integer` but Gofish has it as `string` resulting in unmarshalling errors.
This fixes that.
(Had a problem locally, wanted to help upstream in case someone runs into the same issue eventually)
=> Change Memory Struct (NonVolatileSizeLimitMiB)

redfish/sensor.go, redfish/sensor_test.go
This property has been found to require the larger type with some implementations. This may require some consumers to update their expected return type, but prevents an JSON unmarshalling error when reading the values from the system.
Closes: #361
=> Increase Sensor.ReadingRangeMax to float64

oem/smc/computersystem.go, oem/smc/computersystem_test.go, oem/smc/fixedbootorder.go, oem/smc/fixedbootorder_test.go, oem/smc/nodemanager.go, oem/smc/nodemanager_test.go, redfish/computersystem.go
This adds an OEM version of the ComputerSystem type for Supermicro systems. This enables access to the NodeManager and FixedBootOrder oem-specific objects.
=> Add Supermicro OEM ComputerSystem objects

oem/smc/chassis.go, oem/smc/chassis_test.go, redfish/chassis.go
This adds an OEM-specific Chassis that enables accessing the OEM properties of a chassis.
=> Add Supermicro OEM Chassis object

oem/smc/drive.go, oem/smc/drive_test.go, redfish/drive.go, redfish/drive_test.go
We have some nodes that don't follow the typical indicator light flow that `Update()` would handle. Instead, we have to hit a linked reference (with a variable key, sigh..) from the OEM section.
I'm hoping to expose the `Oem` field in both the `Drive` and the `Drive.Actions` (while also exposing the `Actions`) so that the user can follow that chain when necessary. This allows us to get the right link to where we need to send the `POST` or `PATCH` (also variable, heh) to enable lights for our datacenter folks.
Tests updated to not lose secure erase functionality.
=> redfish/drive: expose oem data and actions

redfish/drive.go
We added EnvironmentMetrics objects, but did not provide a way to fetch them from the links of a Drive. This adds a Drive function to retrieve the EnvironmentMetrics when available.
Closes: #371
=> Add Drive.EnvironmentMetrics() accessor

oem/smc/accountservice.go, oem/smc/accountservice_test.go, redfish/accountservice.go
This adds an OEM version of the AccountService to expose a few OEM-specific properties.
=> Add Supermicro OEM AccountService

oem/smc/updateservice.go, oem/smc/updateservice_test.go, redfish/updateservice.go
This adds an OEM version of the UpdateService to expose some OEM-specific actions and properties.
=> Add Supermicro UpdateService object

oem/smc/dumpservice.go, oem/smc/dumpservice_test.go, oem/smc/updateservice.go, oem/smc/updateservice_test.go
This adds a DumpService OEM object for Supermicro systems.
=> Add Supermicro DumpService object

oem/ami/accountservice.go, oem/ami/accountservice_test.go, oem/ami/computersystem.go, oem/ami/computersystem_test.go, oem/ami/eventservice.go, oem/ami/eventservice_test.go, oem/ami/updateservice.go, oem/ami/updateservice_test.go, oem/smc/updateservice.go, redfish/eventservice.go
This is far from complete, but adds some basic OEM objects for AMI-based Redfish implementations.
=> Add some AMI OEM objects

redfish/sensor.go
We are seeing some implementations using float64 for the generic Sensor.Reading property
=> Increase Sensor.Reading to float64

redfish/computersystem.go, redfish/computersystem_test.go
The `OperatingSystem` property was defined as a string, but this field is actually a link to another object. This updates the definition to parse out the link and adds an accessor method to get the actual `OperatingSystem` object.
Closes: #364
=> Fix OperatingSystem link in ComputerSystem

redfish/coolingunit.go, redfish/environmentmetrics.go
fixes 
- `Reservoirs` typo causes bad json unmarshal
- `EnvironmentMetrics` and `LeakDetections` are not collections but resources of cooling unit
=> Gets instances of resources where relevant in cooling unit

oem/smc/updateservice.go, oem/smc/updateservice_test.go
What a coincidence, it just so happened that I worked on the UpdateService for Supermicro last week :)
This code was tested against a H13SSL server.
The implementation is based on [the documentation](https://www.supermicro.com/manuals/other/redfish-ref-guide-html/Content/general-content/firmware-inventory-update-service.htm#updating-ssl) from Supermicro.
=> Add SSLCert Upload to Supermicro UpdateService

redfish/thermalsubsystem.go
like in PR 381, LeakDetection is an instance of a resource within ThermalSubsystem but overlooked this file when making that change
=> LeakDetection is an instance in ThermalSubsystem

redfish/computersystem.go, redfish/computersystem_test.go
Adds Metrics Property of ProcessorSummary in ComputerSystem
From [data model spec](https://www.dmtf.org/sites/default/files/standards/documents/DSP0268_2024.3.html):
| Property | Type | Notes |
| - | - | - |
| Metrics (v1.7+)  | object  | The link to the metrics associated with all processors in this system.This property shall contain a link to the metrics associated with all processors in this system. See the ProcessorMetrics schema for details on this property. |
=> Add ProcessorSummary Metrics link

common/types.go
as of DSP2046 2024.3 Status contains a Conditions property
fixes #384
=> Add Conditions to Status

redfish/power.go
It appears that there is both a [PowerSupply](https://pkg.go.dev/github.com/stmcginnis/gofish/redfish#PowerSupply) and a [PowerSupplyUnit](https://pkg.go.dev/github.com/stmcginnis/gofish/redfish#PowerSupplyUnit) type, which both represent the same Redfish "PowerSupply" resource.
Unfortunately, `PowerSupply` and `PowerSuppyUnit` each have some features that the other does not. For my current use case, I need some fields that only exist on `PowerSupply` but also require the `Metrics()` method, which is only available on `PowerSupplyUnit`.
I have opted for that path of least resistance here: just adding a link to `PowerSupplyUnitMetrics` from `PowerSupply` (since it's the same underlying Redfish resource schemas, everything parses correctly). Note: there is no `PowerSupplyMetrics`.
Please …
=> Add method to get metrics from PowerSupply

redfish/processor.go
per the spec Ports is defined as a link to the collection of the resource. In keeping with the pattern throughout the Gofish lib Ports() should return the instances of the Ports under processors. (Mostly I've copied the pattern established with `client.serviceroot.Chassis()` :)
=> Ports gets the instances managed by the Processor

redfish/computersystem.go
With the new DMTF Redfish release 2024.4 there is a new [ResetType](https://www.dmtf.org/sites/default/files/standards/documents/DSP2046_2024.4.html#resettype) `FullPowerCycle`.
=> Add new FullPowerCycle ResetType

redfish/accountservice.go
The returned `*ManagerAccount` when using `CreateAccount()` did not have a client set which made using `*ManagerAccount` have a nil reference when attempting to make HTTP calls afterwards.
=> Add client to the returned ManagerAccount on account creation

.golangci.yaml
Lint job started to fail complaining about jsonschema of config (f.e. one of my previous [PRs is ok](https://github.com/stmcginnis/gofish/actions/runs/13303597831/job/37149525323?pr=404#step:1:38), [the other fails](https://github.com/stmcginnis/gofish/actions/runs/13518590958/job/37772547791?pr=406#step:1:38))
Lint job uses v6 version of action and it was updated recently with this PR: https://github.com/golangci/golangci-lint-action/pull/1171 - so the job started to verify the config's schema.
This PR fixes the config:
- removes unsupported property for `nolintlint` - https://golangci-lint.run/usage/linters/#nolintlint
- changes from array to object in `goheader` - https://golangci-lint.run/usage/linters/#goheader
=> Fix golangci config

client.go
When `ClientConfig.HTTPClient` is passed, the `Client.keepAlive` field is not set even if we set `ClientConfig.ReuseConnection`.
With this PR, the `keepAlive` field will be properly set (based on `ClientConfig.ReuseConnection` value) in both cases.
=> Set client.keepAlive flag also for passed HTTPClient

client.go
I use gofish in a custom redfish prometheus exporter. `APIClient` is created for each scrape http request with `ConnectContext` where I pass http request ctx.
If the scrape request is aborted (f.e. when scrape timeout is reached), I discovered the redfish session is not deleted. In some cases it can block access to bmc (when the limit of existing sessions is reached).
When I looked into the code, I see the `APIclient.Logout()` eventually invoke `APIClient.runRawRequestWithHeaders()` where the `APIclient.ctx` is used in `http.NewRequestWithContext` ([link](https://github.com/stmcginnis/gofish/blob/b73be00f1f7cd5a2a9e46e4fc69bae1bf0bf4b25/client.go#L474)) - and this fails with "context canceled" error.
I'd like to be able to clean up the redfish session even when the downstream request is …
=> Allow logout even when APIClient ctx is canceled

redfish/environmentmetrics.go
This PR adds `Oem` property for `EnvironmentMetrics` resource, similarly like in `ProcessorMetrics`
=> Add Oem property to EnvironmentMetrics

common/types.go
This PR adds `Oem` property to `common.Status` struct. (ref: https://www.dmtf.org/sites/default/files/standards/documents/DSP0268_2024.4.html#status)
=> Add Oem property to Status

redfish/processor.go, redfish/processor_test.go
Adding `CacheMemory` link to Processor type. 
ref: https://www.dmtf.org/sites/default/files/standards/documents/DSP0268_2024.4.html#processor-1201
=> Add CacheMemory to Processor resource

redfish/sensor.go, redfish/sensor_test.go
Similar to #362 but for `ReadingRangeMin`.
For some BMCs I was also getting errors like `cannot unmarshal number -1.7976931348623157e+308 into Go struct field .temp.ReadingRangeMin of type float32`
=> Use float64 for Sensor.ReadingRangeMin

common/entity.go, common/entity_test.go
Update payload logic was not aware of things like ",omitempty". This would cause an invalid field name in the PATCH payload to update objects with optional fields. This updates the handling to strip out this string from the JSON property name.
Closes: #431
=> Strip omitempty when formulating object update

redfish/trustedcomponent.go
Redfish TrustedComponents can have a `TPM` object that looks like this:
```json
"TPM": {
"CapabilitiesVendorID": "IFX",
"HardwareInterfaceVendorID": "0x15D1"
},
```
Currently, the gofish TrustedComponent type has a `string` struct field for TPMs, and when using the gofish `ListReferencedTrustedComponents`, the Unmarshal fails.
There is a custom TPM struct that we should use as the type instead
```go
// TPM shall contain TPM-specific information for a trusted component.
type TPM struct {
// CapabilitiesVendorID shall contain an ASCII string of the 4-byte TCG-defined 'TPM Capabilities Vendor ID' for
// this trusted component.
CapabilitiesVendorID string
// HardwareInterfaceVendorID shall contain the TCG-defined 'TPM Hardware Interface Vendor ID' for this trusted
// component with the most …
```
=> fix: TrustedComponent TPM is a json object

common/types.go, redfish/actioninfo.go, redfish/actioninfo_test.go, redfish/logservice.go, redfish/logservice_test.go
Implements ActionInfo per DSP0268 6.3
Also adds action info support to CollectDiagnosticData
I also noticed https://github.com/stmcginnis/gofish/pull/423 (after I implemented it, oops) which also does ActionInfo. I don't mind rebasing to that and just adding the CollectDiagnosticData support, just let me know which is preferred.
=> Add support for ActionInfo and implement for CollectDiagnosticData

common/entity.go, redfish/accountservice.go
I discovered that BMCs send a different ETag on the `/AccountService/Accounts` endpoint, which is used to both list accounts and create a new account. On some BMCs, the ETag is the same for both `/AccountService` and `/AccountService/Accounts`
As a result, `CreateAccount` fails if ETag is properly validated on a BMC. This change adjusts the request to retrieve the proper ETag before creating an account if ETag is enabled
=> Handle etag properly on CreateAccount call

redfish/pciedevice.go
Handles #442. I know this is a vendor issue, but I feel we should be liberal in handling this data. Are you worried that fixing it in one place means we have to handle incorrect specs everywhere?
=> Handle empty arrays for PCIeInterfaces.

common/types.go, common/types_test.go, redfish/resource.go
Gb200's have LocationOrdinalValue as "3"
This creates a custom unmarshal to handle it.
A request looks something like this, adding a custom unmarshaller to handle converting the string to int.
```
"PartLocation": {
"LocationOrdinalValue": "4",
"LocationType": "Slot",
"ServiceLabel": "PSU 4"
}
```
=> Update PartLocation to handle string int.

redfish/actioninfo.go, redfish/chassis.go, redfish/chassis_test.go, redfish/computersystem.go, redfish/computersystem_test.go, redfish/manager.go, redfish/manager_test.go
this change adds support for describing the supported Reset and ResetToDefaults types via ActionInfo in addition to the existing inline AllowableValues
This is implemented here for chassis, manager and computer system
It's implemented as a function called by the user as it issues an additional request, so if the user doesn't care about supported actions, they can choose not to call it. In addition, if AllowableValues are provided, they are always preferred to ActionInfo
=> feat: add support for reset action info
